name = input("What's your name: ")
surname = input("What's your surname: ")
age = input("How old are you: ")
height = input("How tall are you: ")
weight = input("How much do you weigh: ")
print("name:", name)
print("surname:", surname)
print("age:", age)
print("height:", height)
print("weight:", weight)