number_1 = input("Enter a number: ")
number_2 = input("Enter a number: ")
number_3 = input("Enter a number: ")
number_4 = input("Enter a number: ")
number_5 = input("Enter a number: ")
print(int(number_1)+int(number_2)+int(number_3)+int(number_4)+int(number_5))